const router = require('express').Router();
const { initiate, getSession, setShipping, setPayment, processPayment, confirm, cancel } = require('../controllers/checkoutController');
router.post('/initiate', initiate);
router.get('/',          getSession);
router.post('/shipping', setShipping);
router.post('/payment',  setPayment);
router.post('/pay',      processPayment);
router.post('/confirm',  confirm);
router.delete('/',       cancel);
module.exports = router;
