const router = require('express').Router();
const { placeOrder, getOrders, getOrderById, cancelOrder, returnOrder, rejectReturn, approveReturn, issueRefund, getReturnStatus, getOrdersByUser, shipOrder, verifyDeliveryOtp, regenerateDeliveryOtp, regeneratePickupOtp, collectReturn } = require('../controllers/orderController');
router.post('/',                            placeOrder);
router.get('/user/:userId',                 getOrdersByUser);
router.get('/',                             getOrders);
router.get('/:id',                          getOrderById);
router.put('/:id/cancel',                   cancelOrder);
router.put('/:id/ship',                     shipOrder);
router.post('/:id/verify-delivery-otp',     verifyDeliveryOtp);
router.post('/:id/regenerate-delivery-otp', regenerateDeliveryOtp);
router.put('/:id/return',                   returnOrder);
router.put('/:id/reject-return',            rejectReturn);
router.put('/:id/approve-return',           approveReturn);
router.post('/:id/refund',                  issueRefund);
router.post('/:id/regenerate-pickup-otp',   regeneratePickupOtp);
router.post('/:id/collect-return',          collectReturn);
router.get('/:id/return-status',            getReturnStatus);
module.exports = router;
