const router = require('express').Router();
const { getAll, getById, search, select, categories, byCategory, stock } = require('../controllers/productController');
router.get('/',               getAll);
router.get('/search',         search);
router.get('/categories',     categories);
router.get('/category/:name', byCategory);
router.get('/:id/stock',      stock);
router.get('/:id',            getById);
router.post('/:id/select',    select);
module.exports = router;
