const express = require('express');
const app = express();
app.use(express.json());
app.use('/api/auth',     require('./routes/auth'));
app.use('/api/products', require('./routes/products'));
app.use('/api/cart',     require('./routes/cart'));
app.use('/api/checkout', require('./routes/checkout'));
app.use('/api/headphones', require('./routes/headphones'));
app.use('/api/tv',       require('./routes/tv'));
app.use('/api/mobile',   require('./routes/mobile'));
app.use('/api/orders',   require('./routes/orders'));
app.get('/health', (req, res) => res.json({ status: 'ok' }));
module.exports = app;
