const express = require('express');
const app = express();
app.use(express.json());
app.use('/api/auth',     require('./routes/auth'));
app.use('/api/products', require('./routes/products'));
app.use('/api/cart',     require('./routes/cart'));
app.use('/api/checkout', require('./routes/checkout'));
app.use('/api/headphones', require('./routes/headphones'));
app.use('/api/tv',       require('./routes/tv'));
app.use('/api/laptops',  require('./routes/laptops'));
app.use('/api/booking-slots', require('./routes/bookingSlots'));
app.use('/api/orders',   require('./routes/orders'));
app.use('/api/payments', require('./routes/payments'));
app.use('/api/exchanges', require('./routes/exchanges'));
app.use('/api/prescriptions', require('./routes/prescriptions'));
app.use('/api/admin/auth',     require('./routes/adminAuth'));
app.use('/api/admin/checkout', require('./routes/adminCheckout'));
app.get('/health', (req, res) => res.json({ status: 'ok' }));
module.exports = app;
