const express = require('express');
const path = require('path');
const app = express();
app.use(express.json());
app.use('/public', express.static(path.join(__dirname, '..', 'public')));
app.use('/api/auth',     require('./routes/auth'));
app.use('/api/auth/azure-devops', require('./routes/azureDevOpsAuth'));
app.use('/api/auth/sso', require('./routes/sso'));
app.use('/api/products', require('./routes/products'));
app.use('/api/cart',     require('./routes/cart'));
app.use('/api/checkout', require('./routes/checkout'));
app.use('/api/headphones', require('./routes/headphones'));
app.use('/api/tv',       require('./routes/tv'));
app.use('/api/laptops',  require('./routes/laptops'));
app.use('/api/booking-slots', require('./routes/bookingSlots'));
app.use('/api/orders',   require('./routes/orders'));
app.use('/api/payments', require('./routes/payments'));
app.use('/api/exchanges', require('./routes/exchanges'));
app.use('/api/return-shipments', require('./routes/returnShipments'));
app.use('/api/prescriptions', require('./routes/prescriptions'));
app.use('/api/medical-history', require('./routes/medicalHistory'));
app.use('/api/sprints',  require('./routes/sprints'));
app.use('/api/smartmed', require('./routes/smartmedOrders'));
app.use('/api/employees', require('./routes/employees'));
app.use('/api/admin/auth',     require('./routes/adminAuth'));
app.use('/api/admin/checkout', require('./routes/adminCheckout'));
app.get('/health', (req, res) => res.json({ status: 'ok' }));
module.exports = app;
